Add nitay880 to contributors route
OSS-team-zulu/Zulu pull request #7
Opened 2020-05-26 12:54 UTC by Nitay880

Please add me :)

2020-05-26 13:20 UTC, nvgoldin requested changes

2020-05-26 13:20 UTC, nvgoldin commented on backend/tests/test_routes.py
> +        'github_profile': 'https://github.com/Nitay880'}]
don't remove, add another one! :)

2020-05-27 22:35 UTC, Nitay880 commented on backend/tests/test_routes.py
> +        'github_profile': 'https://github.com/Nitay880'}]
done

2020-05-27 22:38 UTC, Nitay880 commented on backend/zulu/db_tools.py
> +def story_db():
well maybe stories need a DB for themselves, 
a goot arch will possibly be
user DB, points DB, stories DB
user ----> [bunch of points] 
point ----->[bunch of stories]

2020-07-07 18:36 UTC, matanel-oren commented
not relevant anymore

2020-07-07 18:36 UTC, closed without merging